#!/usr/bin/env python3
"""Embed Old World unit icons (same source owdeepanalysis uses:
owreference/dist/img/icons/units) as base64 data URIs -> web/icons.js.

Downscaled to 64px so the whole set stays small. Icon name = unit type
lowercased without the UNIT_ prefix (UNIT_HORSE_ARCHER -> horse_archer.png).
"""
import base64, json, os, subprocess, tempfile

SRC = "/Users/dominik/Library/CloudStorage/Dropbox/cc/owreference/dist/img/icons/units"
ROOT = os.path.join(os.path.dirname(__file__), "..")
OUT = os.path.join(ROOT, "web", "icons.js")

# every unit present in data.js that has a matching png
import re
data = open(os.path.join(ROOT, "web", "data.js")).read()
units = sorted(set(re.findall(r'"(UNIT_[A-Z0-9_]+)"', data)))

icons = {}
with tempfile.TemporaryDirectory() as td:
    for u in units:
        slug = u.replace("UNIT_", "").lower()
        p = os.path.join(SRC, slug + ".png")
        if not os.path.exists(p):
            continue
        small = os.path.join(td, slug + ".png")
        subprocess.run(["sips", "-Z", "64", p, "--out", small],
                       check=True, capture_output=True)
        b = base64.b64encode(open(small, "rb").read()).decode()
        icons[u] = "data:image/png;base64," + b

# effect icons (promotions + innate abilities) from icons/effects
EFF_SRC = "/Users/dominik/Library/CloudStorage/Dropbox/cc/owreference/dist/img/icons/effects"
effs = sorted(set(re.findall(r'"(EFFECTUNIT_[A-Z0-9_]+)"', data)))
n_eff = 0
with tempfile.TemporaryDirectory() as td2:
    for e in effs:
        slug = e.replace("EFFECTUNIT_", "").lower()
        pth = os.path.join(EFF_SRC, slug + ".png")
        if not os.path.exists(pth):
            continue
        small = os.path.join(td2, slug + ".png")
        subprocess.run(["sips", "-Z", "40", pth, "--out", small],
                       check=True, capture_output=True)
        icons["EFFECT_" + e.replace("EFFECTUNIT_", "")] =             "data:image/png;base64," + base64.b64encode(open(small, "rb").read()).decode()
        n_eff += 1

with open(OUT, "w") as f:
    f.write("// GENERATED by tools/extract_icons.py — in-game unit icons.\n")
    f.write("var OWICONS = ")
    json.dump(icons, f)
    f.write(";\nif (typeof module !== 'undefined') module.exports = OWICONS;\n")

print(f"wrote {os.path.abspath(OUT)}: {len(icons)} icons ({n_eff} effects), "
      f"{os.path.getsize(OUT)//1024} KB")
missing = [u for u in units if u not in icons]
print("no icon for:", ", ".join(missing) or "none")
