// Puzzle library. Each puzzle is one player turn; goal = objective within the
// order budget. Solutions are verified by solver.js (tools/verify_puzzles.js).
var OWPUZZLES = [
  {
    id: 'overrun-basics',
    name: 'Overrun',
    author: 'owpuzzle',
    brief: 'Kill all three enemies this turn. Your horseman has 3 orders.',
    lesson: 'Shock cavalry ROUT when they kill: they advance into the vacated tile and may act again. Chain your kills.',
    orders: 3,
    radius: 3,
    objective: { kind: 'killAll' },
    units: [
      { player: 0, type: 'UNIT_HORSEMAN', q: -2, r: 0 },
      { player: 1, type: 'UNIT_WARRIOR', q: -1, r: 0, hp: 5 },
      { player: 1, type: 'UNIT_WARRIOR', q: 0, r: 0, hp: 5 },
      { player: 1, type: 'UNIT_WARRIOR', q: 1, r: 0, hp: 5 },
    ],
  },
  {
    id: 'spear-wall',
    name: 'The Spear Wall',
    author: 'owpuzzle',
    brief: 'Kill both enemies this turn with 3 orders.',
    lesson: 'Spearmen are immune to rout — cavalry cannot chain through them. Clear the spear with ranged fire, then charge.',
    orders: 3,
    radius: 3,
    objective: { kind: 'killAll' },
    units: [
      { player: 0, type: 'UNIT_HORSEMAN', q: -2, r: 1 },
      { player: 0, type: 'UNIT_ARCHER', q: -2, r: 0 },
      { player: 1, type: 'UNIT_SPEARMAN', q: 0, r: 0, hp: 4 },
      { player: 1, type: 'UNIT_ARCHER', q: 1, r: 0, hp: 8 },
    ],
  },
  {
    id: 'one-spear-two-kills',
    name: 'One Thrust',
    author: 'owpuzzle',
    brief: 'Kill both enemies this turn. Your spearman has 2 orders.',
    lesson: 'Spearmen PIERCE: their attack strikes through the target, hitting the unit directly behind for 25% damage.',
    orders: 2,
    radius: 3,
    objective: { kind: 'killAll' },
    units: [
      { player: 0, type: 'UNIT_SPEARMAN', q: -1, r: -1 },
      { player: 1, type: 'UNIT_AXEMAN', q: 0, r: 1, hp: 4 },
      { player: 1, type: 'UNIT_ARCHER', q: 0, r: 2, hp: 1 },
    ],
  },
  {
    id: 'the-ford',
    name: 'The Ford',
    author: 'owpuzzle',
    brief: 'Kill the warrior this turn. Your axeman has 3 orders.',
    lesson: 'Melee attacks across a river are halved (-50%). Crossing costs extra movement, but striking from the dry bank is worth it.',
    orders: 3,
    radius: 3,
    objective: { kind: 'killAll' },
    // One continuous river, rim to rim. It wraps the warrior's W/NW/SW edges,
    // so the only unhalved attack comes from the far bank.
    tiles: [
      { q: 1, r: 0, river: [2, 3, 4] },
      { q: 1, r: -1, river: [0] },
      { q: 2, r: -2, river: [5, 0] },
      { q: 3, r: -3, river: [5] },
      { q: 0, r: 1, river: [0] },
      { q: 0, r: 2, river: [1, 0] },
      { q: 0, r: 3, river: [1] },
      { q: -2, r: 1, vegetation: 'VEGETATION_TREES' },
      { q: -1, r: -2, vegetation: 'VEGETATION_TREES' },
      { q: 2, r: 1, height: 'HEIGHT_HILL' },
      { q: 3, r: -2, height: 'HEIGHT_HILL', vegetation: 'VEGETATION_TREES' },
    ],
    units: [
      { player: 0, type: 'UNIT_AXEMAN', q: -1, r: 0 },
      { player: 1, type: 'UNIT_WARRIOR', q: 1, r: 0, hp: 8 },
    ],
  },
];
if (typeof module !== 'undefined') module.exports = OWPUZZLES;
